sudo: true
os: trusty
cache: false
notifications:
  slack:
    rooms:
      secure: pNDmklFPJScDl0F6SDqtFYBj0dgg2MGXa0wKJPpk8JSZsGv3j98osy1y7KF4bOOJoA3CXQsx2Swa6rKKG4glfdD+AV9HN55GZKvHtiFFWjeHHD81xL0nYr5yayTDqSDznbdz9UEBrcKdQDwrh0J3FNJnO2dWiPxu1sLcOAPagiYigGup1EpZLvFSNBSCQdziudzETUVlibE3l/i4/5oNMXGpuAuDYhCHU9V9UIAwpmbmnuvcKbhs2QKJUerJ4BnglBQ0DH4Y4SlV5DY7sL4drtPJuZOz9VsCzEWnV6HNEDdLS8xqb+M05G6XZwJCDeyot5xEd09se3hoZ07MVvYKavJgYe47uPS9a4T08JLuy3QS+Ej6io8gKryLvY5MrErVuPDmbo2fJvF0Mg+GUw7d/ChH2p+8hDdOl7uo9pTyXMXwgV4TtpaJ6GE1KK/Tdh2gVtZGyRet0j803AotbAxGeidzgdGrxhreugTSmZx6VQ4TVtOnXZh0AE0SIMyIcHHQXxPPneniDzaPqlOZ7vL9Y/WNfawi9NhAG0zsRyyCEUCgOEr/apfIGaI9GxJP3gxgHCr8P9wHIC8/8cbq8kyz71lZqcS5IC2kEbT9o1gy1PbASig1ZJImTzwnsYpXsSGrWwkzAAazF0Uk+ARLAesO24mM3VSK44a5AGNcJszvVtk=
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_6e1a2e592e02_key -iv $encrypted_6e1a2e592e02_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/developer-scratch-def.json -a ciorg
  --wait 2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
